import Image from "next/image";
import { Cormorant_Garamond } from "next/font/google";
import {
  SoftwareApplicationJsonLd,
  BreadcrumbJsonLd,
  FAQPageJsonLd,
} from "@/components/seo/json-ld";
import { SEO_CONFIG } from "@/lib/seo.config";

// Load the high-end Cormorant Garamond serif font for the elegant italic typography
const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

// ── FAQ data for structured data + on-page content ──────────────────────────
const FAQ_ITEMS = [
  {
    question: "What is QuellDesk?",
    answer:
      "QuellDesk (also known as Quell Desk) is a free AI-powered LaTeX resume builder. It lets you paste a job description and instantly generates a professionally typeset LaTeX resume — no LaTeX knowledge required. Think of it as the easiest way to get Overleaf-quality resumes without the learning curve.",
  },
  {
    question: "How does QuellDesk's AI resume builder work?",
    answer:
      "Simply paste a job description or describe your target role. QuellDesk's AI analyzes the requirements, generates tailored LaTeX code optimized for ATS (Applicant Tracking Systems), and compiles it into a pixel-perfect PDF. You can preview, edit, and download — all from your browser.",
  },
  {
    question: "Is QuellDesk free to use?",
    answer:
      "Yes, QuellDesk is completely free. You can build unlimited LaTeX resumes, compile them to PDF, and download them at no cost. No credit card required.",
  },
  {
    question: "Do I need to know LaTeX to use QuellDesk?",
    answer:
      "Not at all. QuellDesk is designed for people who want the beautiful typography of LaTeX without learning the syntax. The AI handles all the LaTeX code generation. However, if you do know LaTeX, you can use the built-in editor to fine-tune every detail.",
  },
  {
    question: "How is QuellDesk different from Overleaf?",
    answer:
      "Overleaf is a general-purpose LaTeX editor that requires you to write LaTeX code yourself. QuellDesk is specifically built for resumes and uses AI to generate the LaTeX for you from a job description. It's the best Overleaf alternative for job seekers who want professional results without the technical overhead.",
  },
  {
    question: "Are QuellDesk resumes ATS-friendly?",
    answer:
      "Yes. Every resume generated by QuellDesk is optimized for Applicant Tracking Systems. The LaTeX output produces clean, parseable PDF files that ATS software can read correctly — unlike image-based or heavily designed resume templates.",
  },
];

export default function Home() {
  return (
    <>
      {/* ── Structured Data for Homepage ──────────────────────────────── */}
      <SoftwareApplicationJsonLd />
      <BreadcrumbJsonLd items={[{ name: "Home", url: "/" }]} />
      <FAQPageJsonLd items={FAQ_ITEMS} />

      {/* Outer Border Frame (Beige/Sand luxury editorial feel) */}
      <div className="relative min-h-screen w-full flex flex-col justify-between border-[10px] sm:border-[16px] border-[#dfd3c3] overflow-hidden antialiased bg-[#dfd3c3]">
        
        {/* Full Viewport Background Image with 8px inner border radius */}
        <div className="absolute inset-0 w-full h-full pointer-events-none z-0 rounded-[8px] overflow-hidden">
          <Image
            src="/brand/hero-bg.png"
            alt="QuellDesk Abstract Artistic Background"
            fill
            priority
            sizes="100vw"
            className="object-cover object-center select-none"
          />
          {/* Subtle contrast overlay to enhance readability */}
          <div className="absolute inset-0 bg-black/15 pointer-events-none" />
        </div>

        {/* ── Header Navigation ────────────────────────────────────────── */}
        <header className="relative z-10 w-full px-6 py-6 sm:px-12 flex items-center justify-between">
          
          {/* Left Spacer to maintain balanced layout flow */}
          <div className="w-12 sm:w-16" />

          {/* Centered Elegant Logo */}
          <div className="absolute left-1/2 -translate-x-1/2 flex items-center gap-2 select-none">
            <h1 className={`${cormorant.className} text-3xl sm:text-4xl font-normal tracking-wide text-white lowercase`}>
              {SEO_CONFIG.siteName.toLowerCase()}
            </h1>
            <span className="h-1.5 w-1.5 rounded-full bg-white/40 mt-2" />
          </div>

          {/* Right Action Icons & CTA */}
          <div className="flex items-center gap-4 sm:gap-6">
            {/* Capsule CTA button */}
            <a
              href="/register"
              className="bg-white hover:bg-zinc-100 text-zinc-950 px-5 py-2 sm:px-6 sm:py-2.5 rounded-full text-[10px] sm:text-xs uppercase tracking-[0.15em] font-bold shadow-md transition-all duration-300 hover:scale-105 active:scale-95 text-center font-sans"
            >
              Register
            </a>
          </div>
        </header>

        {/* ── Main Hero Section ────────────────────────────────────────── */}
        <main className="relative z-10 w-full px-6 sm:px-16 flex-grow flex flex-col justify-center">
          
          {/* Main Slogan Container */}
          <div className="relative max-w-4xl pt-12 pb-16 flex flex-col items-start select-none">
            
            {/* Left Hand-drawn Geometric Accents (Styled inline-SVG) */}
            <div className="absolute -left-12 sm:-left-20 top-2 w-12 sm:w-16 h-16 sm:h-20 pointer-events-none opacity-85">
              <svg className="w-full h-full text-white/95" viewBox="0 0 80 80" fill="none">
                <path d="M15 15 L35 25 M15 35 L45 35 M15 55 L35 45" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
                <path d="M50 20 L60 40 L50 60" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="opacity-40" />
              </svg>
            </div>

            {/* Title Line 1 (Modern Sans-serif) */}
            <h2 className="text-white text-5xl sm:text-8xl font-normal tracking-tight leading-none mb-1 sm:mb-2 font-sans select-none">
              LaTeX resumes in their
            </h2>

            {/* Title Line 2 (Luxury Serif Italic) */}
            <h3 className={`${cormorant.className} text-white text-6xl sm:text-9xl italic font-light leading-none select-none pl-6 sm:pl-16`}>
              purest form
            </h3>
          </div>
        </main>

        {/* ── Footer Elements ─────────────────────────────────────────── */}
        <footer className="relative z-10 w-full px-6 pb-6 sm:px-12 sm:pb-8 flex flex-col md:flex-row justify-between items-end gap-6">
          
          {/* Bottom Left: Quick copyright & builder tag */}
          <div className="flex flex-col gap-1 text-[10px] uppercase tracking-[0.2em] font-semibold text-white/70 font-sans">
            <span>© {new Date().getFullYear()} QuellDesk</span>
            <span className="text-white/40">AI-Powered Resume compiler</span>
          </div>

          {/* Bottom Middle: Navigation Links for SEO & Sitelinks */}
          <nav className="flex items-center justify-center gap-4 sm:gap-6 text-[10px] uppercase tracking-[0.2em] font-semibold text-white/70 font-sans">
            <a href="/privacy" className="hover:text-white transition-colors duration-200">
              Privacy Policy
            </a>
            <span className="text-white/20 select-none">•</span>
            <a href="/terms" className="hover:text-white transition-colors duration-200">
              Terms of Service
            </a>
          </nav>

          {/* Bottom Right: High-end explanatory copy paragraph */}
          <div className="max-w-xs md:max-w-md text-right text-white/95 text-[11px] sm:text-xs leading-relaxed font-sans pr-2">
            <p>
              We apply advanced AI to LaTeX compilation in order to elevate your professional narrative. Our system achieves unparalleled levels of visual precision and ATS parsing compatibility.
            </p>
          </div>
        </footer>

      </div>

      {/* ══════════════════════════════════════════════════════════════════
           SEO CONTENT SECTION
           Keyword-rich, indexable content below the hero fold.
           This gives Google real text to rank the page for target queries.
           Styled to match the premium editorial aesthetic.
         ══════════════════════════════════════════════════════════════════ */}
      <div className="bg-[#dfd3c3]">
        <div className="max-w-5xl mx-auto px-6 sm:px-12 py-20 sm:py-28">

          {/* ── About Section ──────────────────────────────────────────── */}
          <section className="mb-20 sm:mb-28">
            <h2 className={`${cormorant.className} text-3xl sm:text-5xl font-light text-zinc-900/90 mb-6 sm:mb-8 tracking-tight`}>
              The AI Resume Builder That Writes LaTeX For You
            </h2>
            <div className="max-w-3xl space-y-5 text-zinc-700 text-sm sm:text-base leading-relaxed font-sans">
              <p>
                <strong>QuellDesk</strong> (Quell Desk) is a free, AI-powered LaTeX resume builder designed for job seekers who want professional typography without the learning curve. Paste a job description, and our AI generates optimized LaTeX code that compiles into a pixel-perfect, ATS-friendly PDF resume — in seconds.
              </p>
              <p>
                Unlike generic resume builders that use rigid templates, QuellDesk harnesses the full power of LaTeX typesetting. The result is a resume with the visual precision of an academic publication and the keyword optimization that modern Applicant Tracking Systems demand. It&apos;s the best <strong>Overleaf alternative</strong> purpose-built for resumes.
              </p>
            </div>
          </section>

          {/* ── How It Works ───────────────────────────────────────────── */}
          <section className="mb-20 sm:mb-28">
            <h2 className={`${cormorant.className} text-3xl sm:text-5xl font-light text-zinc-900/90 mb-10 sm:mb-14 tracking-tight`}>
              How It Works
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-8 sm:gap-12">
              {[
                {
                  step: "01",
                  title: "Paste Your Job Description",
                  text: "Drop in the job listing or describe your target role. Our AI resume generator analyzes the requirements, keywords, and expectations.",
                },
                {
                  step: "02",
                  title: "AI Writes Your LaTeX Resume",
                  text: "QuellDesk's AI engine generates tailored LaTeX code with professional formatting, ATS-optimized structure, and keyword-rich content — no LaTeX knowledge required.",
                },
                {
                  step: "03",
                  title: "Compile & Download PDF",
                  text: "Our cloud-based LaTeX compiler renders your resume into a high-quality PDF. Preview it in the built-in editor, tweak if needed, and download instantly.",
                },
              ].map((item) => (
                <div key={item.step} className="flex flex-col gap-3">
                  <span className={`${cormorant.className} text-5xl sm:text-6xl font-light text-zinc-900/15`}>
                    {item.step}
                  </span>
                  <h3 className="text-zinc-900/85 text-sm sm:text-base font-bold uppercase tracking-[0.1em] font-sans">
                    {item.title}
                  </h3>
                  <p className="text-zinc-600 text-sm leading-relaxed font-sans">
                    {item.text}
                  </p>
                </div>
              ))}
            </div>
          </section>

          {/* ── Why LaTeX for Resumes ───────────────────────────────────── */}
          <section className="mb-20 sm:mb-28">
            <h2 className={`${cormorant.className} text-3xl sm:text-5xl font-light text-zinc-900/90 mb-6 sm:mb-8 tracking-tight`}>
              Why LaTeX Resumes Stand Out
            </h2>
            <div className="max-w-3xl space-y-5 text-zinc-700 text-sm sm:text-base leading-relaxed font-sans">
              <p>
                LaTeX is the gold standard for document typesetting in academia, engineering, and technical fields. A <strong>LaTeX resume</strong> signals attention to detail and technical fluency — qualities hiring managers in software engineering, data science, and research actively look for.
              </p>
              <p>
                But learning LaTeX takes time. QuellDesk eliminates that barrier entirely. Our <strong>AI LaTeX writer</strong> handles syntax, formatting, spacing, and structure while you focus on your story. The output is a clean, ATS-parseable PDF that stands out in both human review and automated screening.
              </p>
              <p>
                Whether you&apos;re a software engineer building your first resume, a researcher converting your CV, or a career changer tailoring your experience to a new field — QuellDesk is the fastest path from job description to professional LaTeX resume.
              </p>
            </div>
          </section>

          {/* ── FAQ Section ────────────────────────────────────────────── */}
          <section className="mb-16 sm:mb-20">
            <h2 className={`${cormorant.className} text-3xl sm:text-5xl font-light text-zinc-900/90 mb-10 sm:mb-14 tracking-tight`}>
              Frequently Asked Questions
            </h2>
            <div className="space-y-8 max-w-3xl">
              {FAQ_ITEMS.map((faq, index) => (
                <div key={index} className="border-t border-zinc-900/10 pt-6">
                  <h3 className="text-zinc-900/85 text-sm sm:text-base font-bold font-sans mb-3">
                    {faq.question}
                  </h3>
                  <p className="text-zinc-600 text-sm leading-relaxed font-sans">
                    {faq.answer}
                  </p>
                </div>
              ))}
            </div>
          </section>

        </div>
      </div>
    </>
  );
}
